// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeFpIcQsqqkzu_7k4KkhuD41AKp0w2E2s',
    appId: '1:777633941122:android:087a5f65591c88bce9969b',
    messagingSenderId: '777633941122',
    projectId: 'eatwise-6df8a',
    storageBucket: 'eatwise-6df8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuNHqv2hVF3QKfiKVHmY9RgkBJf53618U',
    appId: '1:777633941122:ios:b1a8105b470d7fe0e9969b',
    messagingSenderId: '777633941122',
    projectId: 'eatwise-6df8a',
    storageBucket: 'eatwise-6df8a.firebasestorage.app',
    iosClientId: '777633941122-bdmhci2dqn41seo6q6pmef42me9cmug6.apps.googleusercontent.com',
    iosBundleId: 'com.pspyatoo.eatwise',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEsA1HEq5Fk4VSN5BplbW02soNJSoSt_A',
    appId: '1:777633941122:web:ab9dff1f5f95db24e9969b',
    messagingSenderId: '777633941122',
    projectId: 'eatwise-6df8a',
    authDomain: 'eatwise-6df8a.firebaseapp.com',
    storageBucket: 'eatwise-6df8a.firebasestorage.app',
    measurementId: 'G-7D9LXKG306',
  );

}